/*
VARIABLES

app = Application Number
*/

const MIN_TOTAL_DISCOUNT=149;
const MIN_PAYMENT=200;
const MIN_AMOUNT_FINANCED =300;
const GROSS_LTV = 175;

module.exports={MIN_TOTAL_DISCOUNT,MIN_PAYMENT,MIN_AMOUNT_FINANCED,GROSS_LTV}
